# Generated by Django 4.1.1 on 2022-10-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_living_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_kitchens', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_toilets', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='uploads/properties')),
                ('property_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('flats', models.ManyToManyField(blank=True, to='api.flat')),
            ],
        ),
    ]
