# Generated by Django 4.1.1 on 2023-01-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_flat_all_tenants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
    ]
