# Generated by Django 4.1.1 on 2023-01-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_flat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='vacant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
