# Generated by Django 4.1.1 on 2022-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_makepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
