# Generated by Django 4.1.1 on 2023-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_addaccount_user_alter_flat_current_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpenses',
            name='approved_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='approved_date',
            field=models.DateField(auto_now=True),
        ),
    ]
