# Generated by Django 4.1.1 on 2023-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addexpenses_approved_date_makepayment_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
