# Generated by Django 4.1.1 on 2023-02-22 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_makepayment_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='all_managers',
            field=models.ManyToManyField(blank=True, related_name='manager_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
