# Generated by Django 4.1.1 on 2022-12-12 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_managerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddocument',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
