# Generated by Django 4.1.1 on 2022-12-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_landlordtenantdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddocument',
            name='house_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.property'),
        ),
    ]
