# Generated by Django 4.1.1 on 2022-12-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_managerdocument_house_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpayment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.property'),
        ),
    ]
