# Generated by Django 4.1.1 on 2022-12-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_addpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpenses',
            name='flat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flat'),
        ),
    ]
