# Generated by Django 4.1.1 on 2022-12-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_addexpenses_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpayment',
            name='type',
            field=models.CharField(blank=True, choices=[('one-off', 'one-off'), ('recurring', 'recurring'), ('refundable', 'refundable')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PaySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('online payment', 'online_payment'), ('transfer', 'transfer')], max_length=100)),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='documents/salary-payments')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
