# Generated by Django 4.1.1 on 2022-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_addpayment_type_paysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysalary',
            name='manager_verify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
