# Generated by Django 4.1.1 on 2022-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addpayment'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='flat_id',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant_phone_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment',
            field=models.ManyToManyField(related_name='AddPayment', to='api.addpayment'),
        ),
    ]
