# Generated by Django 4.1.1 on 2023-01-03 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'LandLords',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/tenant-pictures')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('annual_salary', models.BigIntegerField(blank=True, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor', models.CharField(blank=True, max_length=100, null=True)),
                ('former_address', models.TextField(blank=True, null=True)),
                ('place_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('position_at_work', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_of_rent', models.TextField(blank=True, null=True)),
                ('account_status', models.BooleanField(blank=True, default=True, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flat', to='api.flat')),
                ('payment', models.ManyToManyField(related_name='AddPayment', to='api.addpayment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='House', to='api.property')),
            ],
            options={
                'verbose_name_plural': 'Tenant',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_salary', models.BigIntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('permit_approval', models.BooleanField(blank=True, default=False, null=True)),
                ('account_status', models.BooleanField(blank=True, default=True, null=True)),
                ('property', models.ManyToManyField(blank=True, to='api.property')),
            ],
            options={
                'verbose_name_plural': 'Manager',
            },
        ),
    ]
