# Generated by Django 4.1.1 on 2023-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_landlord_tenant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/manager-pictures'),
        ),
    ]
