# Generated by Django 4.1.1 on 2022-10-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_annual_salary_tenant_former_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tenant-pictures'),
        ),
    ]
