# Generated by Django 4.1.1 on 2023-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_landlord_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
