# Generated by Django 4.1.1 on 2022-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='permit_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
