# Generated by Django 4.1.1 on 2022-12-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manager_permit_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='account_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='account_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
