# Generated by Django 4.1.1 on 2023-02-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenant_next_of_kin_address_tenant_next_of_kin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='annual_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
