# Generated by Django 4.1.1 on 2022-10-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flat_name", models.CharField(max_length=200)),
                ("number_of_rooms", models.PositiveIntegerField()),
                ("number_of_living_rooms", models.PositiveIntegerField()),
                ("number_of_kitchens", models.PositiveIntegerField()),
                ("number_of_toilets", models.PositiveIntegerField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Flat",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                (
                    "property_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/properties"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("approve", models.BooleanField(default=False)),
                ("flat_details", models.ManyToManyField(to="mperial_apartment.flat")),
            ],
            options={
                "verbose_name_plural": "Property",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=200)),
                ("tenant_phone_number", models.CharField(max_length=12)),
                ("tenant_email", models.EmailField(max_length=100)),
                (
                    "flat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Flat",
                        to="mperial_apartment.flat",
                    ),
                ),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="House",
                        to="mperial_apartment.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tenant",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=100)),
                ("annual_salary", models.BigIntegerField()),
                (
                    "house_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mperial_apartment.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Manager",
            },
        ),
    ]
